export const paths = {
  main: "/",
  category: "/category",
  itemPage: "/item",
  login: "/login",
  signup: "/signup",
  account: "/account",
  order: "/order",
  delivery: "delivery/",
  userOrders: "/orders",
  changeUserData: "/change",
  liked: "/favorites",
  addAddress: "address/",
  updateAddress: "updateAddress/",
};
